// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package userservice

import (
	"context"

	"zero-admin/rpc/proto/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfigAddReq           = sys.ConfigAddReq
	ConfigAddResp          = sys.ConfigAddResp
	ConfigDeleteReq        = sys.ConfigDeleteReq
	ConfigDeleteResp       = sys.ConfigDeleteResp
	ConfigListData         = sys.ConfigListData
	ConfigListReq          = sys.ConfigListReq
	ConfigListResp         = sys.ConfigListResp
	ConfigUpdateReq        = sys.ConfigUpdateReq
	ConfigUpdateResp       = sys.ConfigUpdateResp
	DeptAddReq             = sys.DeptAddReq
	DeptAddResp            = sys.DeptAddResp
	DeptDeleteReq          = sys.DeptDeleteReq
	DeptDeleteResp         = sys.DeptDeleteResp
	DeptListData           = sys.DeptListData
	DeptListReq            = sys.DeptListReq
	DeptListResp           = sys.DeptListResp
	DeptUpdateReq          = sys.DeptUpdateReq
	DeptUpdateResp         = sys.DeptUpdateResp
	DictAddReq             = sys.DictAddReq
	DictAddResp            = sys.DictAddResp
	DictDeleteReq          = sys.DictDeleteReq
	DictDeleteResp         = sys.DictDeleteResp
	DictListData           = sys.DictListData
	DictListReq            = sys.DictListReq
	DictListResp           = sys.DictListResp
	DictUpdateReq          = sys.DictUpdateReq
	DictUpdateResp         = sys.DictUpdateResp
	InfoReq                = sys.InfoReq
	InfoResp               = sys.InfoResp
	JobAddReq              = sys.JobAddReq
	JobAddResp             = sys.JobAddResp
	JobDeleteReq           = sys.JobDeleteReq
	JobDeleteResp          = sys.JobDeleteResp
	JobListData            = sys.JobListData
	JobListReq             = sys.JobListReq
	JobListResp            = sys.JobListResp
	JobUpdateReq           = sys.JobUpdateReq
	JobUpdateResp          = sys.JobUpdateResp
	LoginLogAddReq         = sys.LoginLogAddReq
	LoginLogAddResp        = sys.LoginLogAddResp
	LoginLogDeleteReq      = sys.LoginLogDeleteReq
	LoginLogDeleteResp     = sys.LoginLogDeleteResp
	LoginLogListData       = sys.LoginLogListData
	LoginLogListReq        = sys.LoginLogListReq
	LoginLogListResp       = sys.LoginLogListResp
	LoginReq               = sys.LoginReq
	LoginResp              = sys.LoginResp
	MenuAddReq             = sys.MenuAddReq
	MenuAddResp            = sys.MenuAddResp
	MenuDeleteReq          = sys.MenuDeleteReq
	MenuDeleteResp         = sys.MenuDeleteResp
	MenuListData           = sys.MenuListData
	MenuListReq            = sys.MenuListReq
	MenuListResp           = sys.MenuListResp
	MenuListTree           = sys.MenuListTree
	MenuUpdateReq          = sys.MenuUpdateReq
	MenuUpdateResp         = sys.MenuUpdateResp
	QueryMenuByRoleIdReq   = sys.QueryMenuByRoleIdReq
	QueryMenuByRoleIdResp  = sys.QueryMenuByRoleIdResp
	ReSetPasswordReq       = sys.ReSetPasswordReq
	ReSetPasswordResp      = sys.ReSetPasswordResp
	RoleAddReq             = sys.RoleAddReq
	RoleAddResp            = sys.RoleAddResp
	RoleDeleteReq          = sys.RoleDeleteReq
	RoleDeleteResp         = sys.RoleDeleteResp
	RoleListData           = sys.RoleListData
	RoleListReq            = sys.RoleListReq
	RoleListResp           = sys.RoleListResp
	RoleUpdateReq          = sys.RoleUpdateReq
	RoleUpdateResp         = sys.RoleUpdateResp
	StatisticsLoginLogReq  = sys.StatisticsLoginLogReq
	StatisticsLoginLogResp = sys.StatisticsLoginLogResp
	SysLogAddReq           = sys.SysLogAddReq
	SysLogAddResp          = sys.SysLogAddResp
	SysLogDeleteReq        = sys.SysLogDeleteReq
	SysLogDeleteResp       = sys.SysLogDeleteResp
	SysLogListData         = sys.SysLogListData
	SysLogListReq          = sys.SysLogListReq
	SysLogListResp         = sys.SysLogListResp
	UpdateConfigRoleReq    = sys.UpdateConfigRoleReq
	UpdateConfigRoleResp   = sys.UpdateConfigRoleResp
	UpdateMenuRoleReq      = sys.UpdateMenuRoleReq
	UpdateMenuRoleResp     = sys.UpdateMenuRoleResp
	UserAddReq             = sys.UserAddReq
	UserAddResp            = sys.UserAddResp
	UserDeleteReq          = sys.UserDeleteReq
	UserDeleteResp         = sys.UserDeleteResp
	UserListData           = sys.UserListData
	UserListReq            = sys.UserListReq
	UserListResp           = sys.UserListResp
	UserStatusReq          = sys.UserStatusReq
	UserStatusResp         = sys.UserStatusResp
	UserUpdateReq          = sys.UserUpdateReq
	UserUpdateResp         = sys.UserUpdateResp

	UserService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
		UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error)
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error)
		UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error)
		ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error)
		UpdateUserStatus(ctx context.Context, in *UserStatusReq, opts ...grpc.CallOption) (*UserStatusResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UserAdd(ctx, in, opts...)
}

func (m *defaultUserService) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultUserService) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultUserService) UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UserDelete(ctx, in, opts...)
}

func (m *defaultUserService) ReSetPassword(ctx context.Context, in *ReSetPasswordReq, opts ...grpc.CallOption) (*ReSetPasswordResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.ReSetPassword(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserStatus(ctx context.Context, in *UserStatusReq, opts ...grpc.CallOption) (*UserStatusResp, error) {
	client := sys.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}
