// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddCategoryReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
}

type AddCertReq struct {
	UserId     int64  `json:"userId"`
	CategoryId int64  `json:"categoryId"`
	Name       string `json:"name"`
	CertNo     string `json:"certNo,optional"`
	Issuer     string `json:"issuer,optional"`
	IssueDate  string `json:"issueDate,optional"`
	ExpireDate string `json:"expireDate,optional"`
	Level      string `json:"level,optional"`
	FileUrl    string `json:"fileUrl"`
	FileType   string `json:"fileType"`
}

type AddUserReq struct {
	Name      string `json:"name"`
	Phone     string `json:"phone,optional"`
	Email     string `json:"email,optional"`
	IdCard    string `json:"idCard"`
	Education string `json:"education,optional"`
	Role      int64  `json:"role"`
	Password  string `json:"password"`
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CategoryInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
}

type CategoryListData struct {
	PageResp
	List []CategoryInfo `json:"list"`
}

type CategoryListReq struct {
	PageReq
	Keyword string `form:"keyword,optional"`
}

type CategoryListResp struct {
	BaseResp
	Data CategoryListData `json:"data"`
}

type CertDetailReq struct {
	Id int64 `path:"id"`
}

type CertListData struct {
	PageResp
	List []CertificateInfo `json:"list"`
}

type CertListReq struct {
	PageReq
	UserId     int64  `form:"userId,optional"`
	CategoryId int64  `form:"categoryId,optional"`
	Keyword    string `form:"keyword,optional"`
}

type CertListResp struct {
	BaseResp
	Data CertListData `json:"data"`
}

type CertificateInfo struct {
	Id           int64  `json:"id"`
	UserId       int64  `json:"userId"`
	UserName     string `json:"userName"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	Name         string `json:"name"`
	CertNo       string `json:"certNo"`
	Issuer       string `json:"issuer"`
	IssueDate    string `json:"issueDate"`
	ExpireDate   string `json:"expireDate"`
	Level        string `json:"level"`
	FileUrl      string `json:"fileUrl"`
	FileType     string `json:"fileType"`
	ThumbUrl     string `json:"thumbUrl"`
	Status       int64  `json:"status"`
}

type CleanData struct {
	DeletedFiles int64 `json:"deletedFiles"`
}

type CleanResp struct {
	BaseResp
	Data CleanData `json:"data"`
}

type DownloadData struct {
	Url string `json:"url"`
}

type DownloadResp struct {
	BaseResp
	Data DownloadData `json:"data"`
}

type DeleteReq struct {
	Id int64 `json:"id"`
}

type ExcelFailItem struct {
	Row    int64  `json:"row"`
	Reason string `json:"reason"`
	Data   string `json:"data"`
}

type ExcelImportData struct {
	Total    int64           `json:"total"`
	Success  int64           `json:"success"`
	Failed   int64           `json:"failed"`
	FailList []ExcelFailItem `json:"failList"`
}

type ExcelImportReq struct {
	File []byte `form:"file"`
}

type ExcelImportResp struct {
	BaseResp
	Data ExcelImportData `json:"data"`
}

type ExportTaskData struct {
	TaskId int64 `json:"taskId"`
}

type ExportTaskReq struct {
	PreviewReq
	WatermarkText string `json:"watermarkText,optional"`
}

type ExportTaskResp struct {
	BaseResp
	Data ExportTaskData `json:"data"`
}

type LoginData struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Data LoginData `json:"data"`
}

type PageReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type PageResp struct {
	Total int64 `json:"total"`
	Page  int64 `json:"page"`
}

type PreviewCategory struct {
	CategoryCode string `json:"categoryCode"`
	CategoryName string `json:"categoryName"`
	HasCert      bool   `json:"hasCert"`
	CertId       int64  `json:"certId"`
	CertName     string `json:"certName"`
}

type PreviewData struct {
	Users []PreviewUser `json:"users"`
}

type PreviewReq struct {
	UserIds       []int64  `json:"userIds"`
	CategoryCodes []string `json:"categoryCodes"`
}

type PreviewResp struct {
	BaseResp
	Data PreviewData `json:"data"`
}

type PreviewUser struct {
	UserId     int64             `json:"userId"`
	UserName   string            `json:"userName"`
	Categories []PreviewCategory `json:"categories"`
}

type TaskListData struct {
	PageResp
	List []TaskStatusData `json:"list"`
}

type TaskListReq struct {
	PageReq
}

type TaskListResp struct {
	BaseResp
	Data TaskListData `json:"data"`
}

type TaskStatusData struct {
	Id          int64  `json:"id"`
	TaskName    string `json:"taskName"`
	UserCount   int64  `json:"userCount"`
	CertCount   int64  `json:"certCount"`
	MissCount   int64  `json:"missCount"`
	Status      int64  `json:"status"`
	FailReason  string `json:"failReason"`
	FileUrl     string `json:"fileUrl"`
	CreatedAt   string `json:"createdAt"`
	CompletedAt string `json:"completedAt"`
}

type TaskStatusReq struct {
	Id int64 `path:"id"`
}

type TaskStatusResp struct {
	BaseResp
	Data TaskStatusData `json:"data"`
}

type TemplateData struct {
	Url string `json:"url"`
}

type TemplateResp struct {
	BaseResp
	Data TemplateData `json:"data"`
}

type UpdateCategoryReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status"`
}

type UpdateCertReq struct {
	Id         int64  `json:"id"`
	CategoryId int64  `json:"categoryId"`
	Name       string `json:"name"`
	CertNo     string `json:"certNo,optional"`
	Issuer     string `json:"issuer,optional"`
	IssueDate  string `json:"issueDate,optional"`
	ExpireDate string `json:"expireDate,optional"`
	Level      string `json:"level,optional"`
	FileUrl    string `json:"fileUrl,optional"`
	FileType   string `json:"fileType,optional"`
	Status     int64  `json:"status"`
}

type UpdateUserReq struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone,optional"`
	Email     string `json:"email,optional"`
	IdCard    string `json:"idCard"`
	Education string `json:"education,optional"`
	Role      int64  `json:"role"`
	Status    int64  `json:"status"`
	Password  string `json:"password,optional"`
}

type UploadData struct {
	Url      string `json:"url"`
	FileType string `json:"fileType"`
}

type UploadReq struct {
	File []byte `form:"file"`
}

type UploadResp struct {
	BaseResp
	Data UploadData `json:"data"`
}

type UserDetailReq struct {
	Id int64 `path:"id"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	IdCard    string `json:"idCard"`
	Education string `json:"education"`
	Role      int64  `json:"role"`
	Status    int64  `json:"status"`
}

type UserInfoResp struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type UserListData struct {
	PageResp
	List []UserInfo `json:"list"`
}

type UserListReq struct {
	PageReq
	Keyword string `form:"keyword,optional"`
}

type UserListResp struct {
	BaseResp
	Data UserListData `json:"data"`
}
