// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/DemoLiang/hridoc/api/internal/middleware"
	"github.com/DemoLiang/hridoc/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func corsMiddleware(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")
		if origin == "" {
			origin = "*"
		}
		w.Header().Set("Access-Control-Allow-Origin", origin)
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
		w.Header().Set("Access-Control-Allow-Credentials", "true")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next(w, r)
	}
}

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	jwt := middleware.JWTAuth(serverCtx.Config)
	opLog := middleware.OperationLog(serverCtx)
	cors := rest.Middleware(corsMiddleware)

	server.AddRoutes(rest.WithMiddlewares([]rest.Middleware{cors}, rest.Route{
		Method:  http.MethodPost,
		Path:    "/api/login",
		Handler: loginHandler(serverCtx),
	}))

	protectedRoutes := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/api/category/add",
			Handler: addCategoryHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/category/delete",
			Handler: deleteCategoryHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/category/detail/:id",
			Handler: getCategoryDetailHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/category/list",
			Handler: getCategoryListHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/category/update",
			Handler: updateCategoryHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/cert/add",
			Handler: addCertHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/cert/delete",
			Handler: deleteCertHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/cert/delete/batch",
			Handler: batchDeleteCertHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/cert/preview",
			Handler: previewCertHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/cert/detail/:id",
			Handler: getCertDetailHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/cert/list",
			Handler: getCertListHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/cert/update",
			Handler: updateCertHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/clean",
			Handler: cleanOldExportsHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/excel/import",
			Handler: importExcelHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/excel/template",
			Handler: downloadTemplateHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/excel/template/download",
			Handler: downloadTemplateFileHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/export",
			Handler: createExportTaskHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/watermark/preview",
			Handler: watermarkPreviewHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/preview",
			Handler: previewHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/task/download/:id",
			Handler: getTaskDownloadHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/task/download/:id/file",
			Handler: getTaskDownloadFileHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/task/list",
			Handler: getTaskListHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/task/status/:id",
			Handler: getTaskStatusHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/file/proxy",
			Handler: fileProxyHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/upload",
			Handler: uploadFileHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/user/add",
			Handler: addUserHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/user/delete",
			Handler: deleteUserHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/user/detail/:id",
			Handler: getUserDetailHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/user/info",
			Handler: getUserInfoHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/user/list",
			Handler: getUserListHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/user/update",
			Handler: updateUserHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/api/operation-log/list",
			Handler: getOperationLogListHandler(serverCtx),
		},
	}
	server.AddRoutes(rest.WithMiddlewares([]rest.Middleware{jwt, opLog}, protectedRoutes...))
}
