// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package syslogservice

import (
	"context"

	"zero-admin/rpc/proto/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfigAddReq           = sys.ConfigAddReq
	ConfigAddResp          = sys.ConfigAddResp
	ConfigDeleteReq        = sys.ConfigDeleteReq
	ConfigDeleteResp       = sys.ConfigDeleteResp
	ConfigListData         = sys.ConfigListData
	ConfigListReq          = sys.ConfigListReq
	ConfigListResp         = sys.ConfigListResp
	ConfigUpdateReq        = sys.ConfigUpdateReq
	ConfigUpdateResp       = sys.ConfigUpdateResp
	DeptAddReq             = sys.DeptAddReq
	DeptAddResp            = sys.DeptAddResp
	DeptDeleteReq          = sys.DeptDeleteReq
	DeptDeleteResp         = sys.DeptDeleteResp
	DeptListData           = sys.DeptListData
	DeptListReq            = sys.DeptListReq
	DeptListResp           = sys.DeptListResp
	DeptUpdateReq          = sys.DeptUpdateReq
	DeptUpdateResp         = sys.DeptUpdateResp
	DictAddReq             = sys.DictAddReq
	DictAddResp            = sys.DictAddResp
	DictDeleteReq          = sys.DictDeleteReq
	DictDeleteResp         = sys.DictDeleteResp
	DictListData           = sys.DictListData
	DictListReq            = sys.DictListReq
	DictListResp           = sys.DictListResp
	DictUpdateReq          = sys.DictUpdateReq
	DictUpdateResp         = sys.DictUpdateResp
	InfoReq                = sys.InfoReq
	InfoResp               = sys.InfoResp
	JobAddReq              = sys.JobAddReq
	JobAddResp             = sys.JobAddResp
	JobDeleteReq           = sys.JobDeleteReq
	JobDeleteResp          = sys.JobDeleteResp
	JobListData            = sys.JobListData
	JobListReq             = sys.JobListReq
	JobListResp            = sys.JobListResp
	JobUpdateReq           = sys.JobUpdateReq
	JobUpdateResp          = sys.JobUpdateResp
	LoginLogAddReq         = sys.LoginLogAddReq
	LoginLogAddResp        = sys.LoginLogAddResp
	LoginLogDeleteReq      = sys.LoginLogDeleteReq
	LoginLogDeleteResp     = sys.LoginLogDeleteResp
	LoginLogListData       = sys.LoginLogListData
	LoginLogListReq        = sys.LoginLogListReq
	LoginLogListResp       = sys.LoginLogListResp
	LoginReq               = sys.LoginReq
	LoginResp              = sys.LoginResp
	MenuAddReq             = sys.MenuAddReq
	MenuAddResp            = sys.MenuAddResp
	MenuDeleteReq          = sys.MenuDeleteReq
	MenuDeleteResp         = sys.MenuDeleteResp
	MenuListData           = sys.MenuListData
	MenuListReq            = sys.MenuListReq
	MenuListResp           = sys.MenuListResp
	MenuListTree           = sys.MenuListTree
	MenuUpdateReq          = sys.MenuUpdateReq
	MenuUpdateResp         = sys.MenuUpdateResp
	QueryMenuByRoleIdReq   = sys.QueryMenuByRoleIdReq
	QueryMenuByRoleIdResp  = sys.QueryMenuByRoleIdResp
	ReSetPasswordReq       = sys.ReSetPasswordReq
	ReSetPasswordResp      = sys.ReSetPasswordResp
	RoleAddReq             = sys.RoleAddReq
	RoleAddResp            = sys.RoleAddResp
	RoleDeleteReq          = sys.RoleDeleteReq
	RoleDeleteResp         = sys.RoleDeleteResp
	RoleListData           = sys.RoleListData
	RoleListReq            = sys.RoleListReq
	RoleListResp           = sys.RoleListResp
	RoleUpdateReq          = sys.RoleUpdateReq
	RoleUpdateResp         = sys.RoleUpdateResp
	StatisticsLoginLogReq  = sys.StatisticsLoginLogReq
	StatisticsLoginLogResp = sys.StatisticsLoginLogResp
	SysLogAddReq           = sys.SysLogAddReq
	SysLogAddResp          = sys.SysLogAddResp
	SysLogDeleteReq        = sys.SysLogDeleteReq
	SysLogDeleteResp       = sys.SysLogDeleteResp
	SysLogListData         = sys.SysLogListData
	SysLogListReq          = sys.SysLogListReq
	SysLogListResp         = sys.SysLogListResp
	UpdateConfigRoleReq    = sys.UpdateConfigRoleReq
	UpdateConfigRoleResp   = sys.UpdateConfigRoleResp
	UpdateMenuRoleReq      = sys.UpdateMenuRoleReq
	UpdateMenuRoleResp     = sys.UpdateMenuRoleResp
	UserAddReq             = sys.UserAddReq
	UserAddResp            = sys.UserAddResp
	UserDeleteReq          = sys.UserDeleteReq
	UserDeleteResp         = sys.UserDeleteResp
	UserListData           = sys.UserListData
	UserListReq            = sys.UserListReq
	UserListResp           = sys.UserListResp
	UserStatusReq          = sys.UserStatusReq
	UserStatusResp         = sys.UserStatusResp
	UserUpdateReq          = sys.UserUpdateReq
	UserUpdateResp         = sys.UserUpdateResp

	SysLogService interface {
		SysLogAdd(ctx context.Context, in *SysLogAddReq, opts ...grpc.CallOption) (*SysLogAddResp, error)
		SysLogList(ctx context.Context, in *SysLogListReq, opts ...grpc.CallOption) (*SysLogListResp, error)
		SysLogDelete(ctx context.Context, in *SysLogDeleteReq, opts ...grpc.CallOption) (*SysLogDeleteResp, error)
	}

	defaultSysLogService struct {
		cli zrpc.Client
	}
)

func NewSysLogService(cli zrpc.Client) SysLogService {
	return &defaultSysLogService{
		cli: cli,
	}
}

func (m *defaultSysLogService) SysLogAdd(ctx context.Context, in *SysLogAddReq, opts ...grpc.CallOption) (*SysLogAddResp, error) {
	client := sys.NewSysLogServiceClient(m.cli.Conn())
	return client.SysLogAdd(ctx, in, opts...)
}

func (m *defaultSysLogService) SysLogList(ctx context.Context, in *SysLogListReq, opts ...grpc.CallOption) (*SysLogListResp, error) {
	client := sys.NewSysLogServiceClient(m.cli.Conn())
	return client.SysLogList(ctx, in, opts...)
}

func (m *defaultSysLogService) SysLogDelete(ctx context.Context, in *SysLogDeleteReq, opts ...grpc.CallOption) (*SysLogDeleteResp, error) {
	client := sys.NewSysLogServiceClient(m.cli.Conn())
	return client.SysLogDelete(ctx, in, opts...)
}
