// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	certCategoryFieldNames          = builder.RawFieldNames(&CertCategory{})
	certCategoryRows                = strings.Join(certCategoryFieldNames, ",")
	certCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(certCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	certCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(certCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCertCategoryIdPrefix   = "cache:certCategory:id:"
	cacheCertCategoryCodePrefix = "cache:certCategory:code:"
)

type (
	certCategoryModel interface {
		Insert(ctx context.Context, data *CertCategory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CertCategory, error)
		FindOneByCode(ctx context.Context, code string) (*CertCategory, error)
		Update(ctx context.Context, data *CertCategory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCertCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	CertCategory struct {
		Id          int64          `db:"id"`          // 主键ID
		Name        string         `db:"name"`        // 类型名称
		Code        string         `db:"code"`        // 类型编码
		Description sql.NullString `db:"description"` // 描述
		Status      int64          `db:"status"`      // 状态：1-启用，2-禁用
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newCertCategoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCertCategoryModel {
	return &defaultCertCategoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`cert_category`",
	}
}

func (m *defaultCertCategoryModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	certCategoryCodeKey := fmt.Sprintf("%s%v", cacheCertCategoryCodePrefix, data.Code)
	certCategoryIdKey := fmt.Sprintf("%s%v", cacheCertCategoryIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, certCategoryCodeKey, certCategoryIdKey)
	return err
}

func (m *defaultCertCategoryModel) FindOne(ctx context.Context, id int64) (*CertCategory, error) {
	certCategoryIdKey := fmt.Sprintf("%s%v", cacheCertCategoryIdPrefix, id)
	var resp CertCategory
	err := m.QueryRowCtx(ctx, &resp, certCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", certCategoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCertCategoryModel) FindOneByCode(ctx context.Context, code string) (*CertCategory, error) {
	certCategoryCodeKey := fmt.Sprintf("%s%v", cacheCertCategoryCodePrefix, code)
	var resp CertCategory
	err := m.QueryRowIndexCtx(ctx, &resp, certCategoryCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", certCategoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCertCategoryModel) Insert(ctx context.Context, data *CertCategory) (sql.Result, error) {
	certCategoryCodeKey := fmt.Sprintf("%s%v", cacheCertCategoryCodePrefix, data.Code)
	certCategoryIdKey := fmt.Sprintf("%s%v", cacheCertCategoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, certCategoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.Description, data.Status)
	}, certCategoryCodeKey, certCategoryIdKey)
	return ret, err
}

func (m *defaultCertCategoryModel) Update(ctx context.Context, newData *CertCategory) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	certCategoryCodeKey := fmt.Sprintf("%s%v", cacheCertCategoryCodePrefix, data.Code)
	certCategoryIdKey := fmt.Sprintf("%s%v", cacheCertCategoryIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, certCategoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Description, newData.Status, newData.Id)
	}, certCategoryCodeKey, certCategoryIdKey)
	return err
}

func (m *defaultCertCategoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCertCategoryIdPrefix, primary)
}

func (m *defaultCertCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", certCategoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCertCategoryModel) tableName() string {
	return m.table
}
