// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	certificateFieldNames          = builder.RawFieldNames(&Certificate{})
	certificateRows                = strings.Join(certificateFieldNames, ",")
	certificateRowsExpectAutoSet   = strings.Join(stringx.Remove(certificateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	certificateRowsWithPlaceHolder = strings.Join(stringx.Remove(certificateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCertificateIdPrefix = "cache:certificate:id:"
)

type (
	certificateModel interface {
		Insert(ctx context.Context, data *Certificate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Certificate, error)
		Update(ctx context.Context, data *Certificate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCertificateModel struct {
		sqlc.CachedConn
		table string
	}

	Certificate struct {
		Id         int64          `db:"id"`          // 主键ID
		UserId     int64          `db:"user_id"`     // 关联用户ID
		CategoryId int64          `db:"category_id"` // 关联证件类型ID
		Name       string         `db:"name"`        // 证书名称
		CertNo     sql.NullString `db:"cert_no"`     // 证书编号
		Issuer     sql.NullString `db:"issuer"`      // 发证机构
		IssueDate  sql.NullTime   `db:"issue_date"`  // 发证日期
		ExpireDate sql.NullTime   `db:"expire_date"` // 有效期至
		Level      sql.NullString `db:"level"`       // 证书等级（初中高级）
		FileUrl    string         `db:"file_url"`    // MinIO 文件URL
		FileType   string         `db:"file_type"`   // 文件类型：image/pdf
		ThumbUrl   sql.NullString `db:"thumb_url"`   // 缩略图URL
		Status     int64          `db:"status"`      // 状态：1-正常，2-过期
		CreatedAt  time.Time      `db:"created_at"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newCertificateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCertificateModel {
	return &defaultCertificateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`certificate`",
	}
}

func (m *defaultCertificateModel) Delete(ctx context.Context, id int64) error {
	certificateIdKey := fmt.Sprintf("%s%v", cacheCertificateIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, certificateIdKey)
	return err
}

func (m *defaultCertificateModel) FindOne(ctx context.Context, id int64) (*Certificate, error) {
	certificateIdKey := fmt.Sprintf("%s%v", cacheCertificateIdPrefix, id)
	var resp Certificate
	err := m.QueryRowCtx(ctx, &resp, certificateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", certificateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCertificateModel) Insert(ctx context.Context, data *Certificate) (sql.Result, error) {
	certificateIdKey := fmt.Sprintf("%s%v", cacheCertificateIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, certificateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CategoryId, data.Name, data.CertNo, data.Issuer, data.IssueDate, data.ExpireDate, data.Level, data.FileUrl, data.FileType, data.ThumbUrl, data.Status)
	}, certificateIdKey)
	return ret, err
}

func (m *defaultCertificateModel) Update(ctx context.Context, data *Certificate) error {
	certificateIdKey := fmt.Sprintf("%s%v", cacheCertificateIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, certificateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.CategoryId, data.Name, data.CertNo, data.Issuer, data.IssueDate, data.ExpireDate, data.Level, data.FileUrl, data.FileType, data.ThumbUrl, data.Status, data.Id)
	}, certificateIdKey)
	return err
}

func (m *defaultCertificateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCertificateIdPrefix, primary)
}

func (m *defaultCertificateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", certificateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCertificateModel) tableName() string {
	return m.table
}
