// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	exportTaskFieldNames          = builder.RawFieldNames(&ExportTask{})
	exportTaskRows                = strings.Join(exportTaskFieldNames, ",")
	exportTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(exportTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	exportTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(exportTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheExportTaskIdPrefix = "cache:exportTask:id:"
)

type (
	exportTaskModel interface {
		Insert(ctx context.Context, data *ExportTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ExportTask, error)
		Update(ctx context.Context, data *ExportTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultExportTaskModel struct {
		sqlc.CachedConn
		table string
	}

	ExportTask struct {
		Id              int64          `db:"id"`               // 主键ID
		TaskName        sql.NullString `db:"task_name"`        // 任务名称
		UserCount       int64          `db:"user_count"`       // 涉及人数
		CertCount       int64          `db:"cert_count"`       // 匹配证件数
		MissCount       int64          `db:"miss_count"`       // 缺证人数
		WatermarkConfig sql.NullString `db:"watermark_config"` // 水印配置
		FileUrl         sql.NullString `db:"file_url"`         // 生成的压缩包URL
		Status          int64          `db:"status"`           // 状态：1-处理中，2-完成，3-失败
		FailReason      sql.NullString `db:"fail_reason"`      // 失败原因
		CreatedBy       int64          `db:"created_by"`       // 创建人ID
		CreatedAt       time.Time      `db:"created_at"`
		CompletedAt     sql.NullTime   `db:"completed_at"` // 完成时间
	}
)

func newExportTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultExportTaskModel {
	return &defaultExportTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`export_task`",
	}
}

func (m *defaultExportTaskModel) Delete(ctx context.Context, id int64) error {
	exportTaskIdKey := fmt.Sprintf("%s%v", cacheExportTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, exportTaskIdKey)
	return err
}

func (m *defaultExportTaskModel) FindOne(ctx context.Context, id int64) (*ExportTask, error) {
	exportTaskIdKey := fmt.Sprintf("%s%v", cacheExportTaskIdPrefix, id)
	var resp ExportTask
	err := m.QueryRowCtx(ctx, &resp, exportTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", exportTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExportTaskModel) Insert(ctx context.Context, data *ExportTask) (sql.Result, error) {
	exportTaskIdKey := fmt.Sprintf("%s%v", cacheExportTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, exportTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TaskName, data.UserCount, data.CertCount, data.MissCount, data.WatermarkConfig, data.FileUrl, data.Status, data.FailReason, data.CreatedBy, data.CompletedAt)
	}, exportTaskIdKey)
	return ret, err
}

func (m *defaultExportTaskModel) Update(ctx context.Context, data *ExportTask) error {
	exportTaskIdKey := fmt.Sprintf("%s%v", cacheExportTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, exportTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TaskName, data.UserCount, data.CertCount, data.MissCount, data.WatermarkConfig, data.FileUrl, data.Status, data.FailReason, data.CreatedBy, data.CompletedAt, data.Id)
	}, exportTaskIdKey)
	return err
}

func (m *defaultExportTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheExportTaskIdPrefix, primary)
}

func (m *defaultExportTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", exportTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultExportTaskModel) tableName() string {
	return m.table
}
