// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/hridoc/internal/logic/deptservice"
	"zero-admin/rpc/hridoc/internal/svc"
	"zero-admin/rpc/proto/sys"
)

type DeptServiceServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedDeptServiceServer
}

func NewDeptServiceServer(svcCtx *svc.ServiceContext) *DeptServiceServer {
	return &DeptServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeptServiceServer) DeptAdd(ctx context.Context, in *sys.DeptAddReq) (*sys.DeptAddResp, error) {
	l := deptservicelogic.NewDeptAddLogic(ctx, s.svcCtx)
	return l.DeptAdd(in)
}

func (s *DeptServiceServer) DeptList(ctx context.Context, in *sys.DeptListReq) (*sys.DeptListResp, error) {
	l := deptservicelogic.NewDeptListLogic(ctx, s.svcCtx)
	return l.DeptList(in)
}

func (s *DeptServiceServer) DeptUpdate(ctx context.Context, in *sys.DeptUpdateReq) (*sys.DeptUpdateResp, error) {
	l := deptservicelogic.NewDeptUpdateLogic(ctx, s.svcCtx)
	return l.DeptUpdate(in)
}

func (s *DeptServiceServer) DeptDelete(ctx context.Context, in *sys.DeptDeleteReq) (*sys.DeptDeleteResp, error) {
	l := deptservicelogic.NewDeptDeleteLogic(ctx, s.svcCtx)
	return l.DeptDelete(in)
}
