// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/hridoc/internal/logic/loginlogservice"
	"zero-admin/rpc/hridoc/internal/svc"
	"zero-admin/rpc/proto/sys"
)

type LoginLogServiceServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedLoginLogServiceServer
}

func NewLoginLogServiceServer(svcCtx *svc.ServiceContext) *LoginLogServiceServer {
	return &LoginLogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginLogServiceServer) LoginLogAdd(ctx context.Context, in *sys.LoginLogAddReq) (*sys.LoginLogAddResp, error) {
	l := loginlogservicelogic.NewLoginLogAddLogic(ctx, s.svcCtx)
	return l.LoginLogAdd(in)
}

func (s *LoginLogServiceServer) LoginLogList(ctx context.Context, in *sys.LoginLogListReq) (*sys.LoginLogListResp, error) {
	l := loginlogservicelogic.NewLoginLogListLogic(ctx, s.svcCtx)
	return l.LoginLogList(in)
}

func (s *LoginLogServiceServer) LoginLogDelete(ctx context.Context, in *sys.LoginLogDeleteReq) (*sys.LoginLogDeleteResp, error) {
	l := loginlogservicelogic.NewLoginLogDeleteLogic(ctx, s.svcCtx)
	return l.LoginLogDelete(in)
}

// 统计后台用户登录---(查询当天登录人数（根据IP,统计当前周登录人数（根据IP）,统计当前月登录人数（根据IP）)
func (s *LoginLogServiceServer) StatisticsLoginLog(ctx context.Context, in *sys.StatisticsLoginLogReq) (*sys.StatisticsLoginLogResp, error) {
	l := loginlogservicelogic.NewStatisticsLoginLogLogic(ctx, s.svcCtx)
	return l.StatisticsLoginLog(in)
}
